---
title: "l05-06"
author: "Shun Nakanowatari"
date: "2022/4/26"
output: html_document
---

```{r leaflet map example}
library(leaflet)
popup = c("Kusatsu", "Beppu", "Noboribetsu")
leaflet() %>%
  addProviderTiles("OpenTopoMap") %>%
  addCircleMarkers(color = 'red', lng = c(138.59664, 131.50599, 141.14410),
             lat = c(36.62376, 33.27758, 42.49482), 
             popup = popup)
```

```{r load package and data}
library(sf)
library(raster)
library(spData)
library(spDataLarge)
```

```{r world}
world
plot(world)
names(world)

```

```{r world life_exp}
#world["lifeExp"]
#↑↓same
world %>% dplyr::select(lifeExp) #dplyrの中のselect関数を使うという意味．Rasterの中にもselect関数が存在しているため．

#st_drop_geometry(world["lifeExp"])
#↑↓same
world %>% dplyr::select(lifeExp) %>% st_drop_geometry()

class(world)
plot(world["lifeExp"])
```

```{r union}
world_asia = world[world$continent == "Asia", ]
asia = st_union(world_asia)
#> although coordinates are longitude/latitude, st_union assumes that they are planar
world_asia
asia #Geometryが1つだけになっている
plot(world_asia)
plot(asia)

plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "red")
```
```{r multipoint}
multipoint_matrix = rbind(c(5, 2), c(1, 3), c(3, 4), c(3, 2)) 
multi_point <- st_multipoint(multipoint_matrix)

multipoint_matrix
class(multi_point)
multi_point
```

```{r 2.2.8}
lnd_point = st_point(c(0.1, 51.5))                 # sfg object
class(lnd_point)
lnd_geom = st_sfc(lnd_point, crs = 4326)           # sfc object
lnd_attrib = data.frame(                           # data.frame object
  name = "London",
  temperature = 25,
  date = as.Date("2017-06-21")
  )
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom)    # sf object
```

```{r　2.3 raster}
#load data
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath)
new_raster
plot(new_raster)

multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
multi_raster_file
r_brick = brick(multi_raster_file)
r_brick
plot(r_brick)
```


```{r ndvi}
ndvi = (r_brick[[4]] - r_brick[[3]]) / (r_brick[[3]] + r_brick[[4]])
plot(ndvi)
```

```{r load library}
library(sf)
library(raster)
library(dplyr)
library(stringr) # for working with strings (pattern matching)
library(tidyr)   # for unite() and separate()
library(spData)
```

```{r 3.2.1}
sel_area = world$area_km2 < 10000
small_countries = world[sel_area, ]
small_countries
plot(small_countries["pop"])
#↑↓same
world %>% 
  filter(area_km2 < 10000) %>%
  dplyr::select(pop) %>%
  plot()
```

```{r top n}
##1.GDPperCapitaがtop10の国をピックアップして地図化してみましょう．
world %>% 
  dplyr::select(gdpPercap) %>%
  top_n(10, gdpPercap) %>%
  plot()

##2.GDPperCapitaがworst10の国をピックアップして地図化してみましょう．
world %>% 
  dplyr::select(gdpPercap) %>%
  top_n(-10, gdpPercap) %>%
  plot()

##3.日本はGDPperCapitaで上から何番目でしょう．
#gdpPercapをsortしたい
world %>% dplyr::select(name_long, gdpPercap)
gdp_sort <- world %>% arrange(desc(gdpPercap)) %>% dplyr::select(gdpPercap) %>% st_drop_geometry()

#日本のgdpPercapを取り出したい
jp_gdp <- world %>% filter(name_long == "Japan") %>%
  dplyr::select(gdpPercap) %>%
  st_drop_geometry() %>%
  as.numeric()

#gdpPercapが上から何番目か調べたい
which(gdp_sort == jp_gdp)
##22番目
```
